name: Checkstyle

on:
  # Triggers the workflow on pull request events for the main branch
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: Temurin

      - name: Run maven-checkstyle-plugin
        run: |
          mvn -B checkstyle:check -D env=ci
