# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME # env variable which is set in deploy step
        server-password: MAVEN_PASSWORD # env variable which is set in deploy step
        gpg-private-key: MAVEN_GPG_PRIVATE_KEY # env variable which is set in deploy step
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable which is set in deploy step

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Maven Central
      run: mvn -B deploy -D env=ci -P release
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
